# Generated by Django 2.1 on 2018-09-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gv', '0002_delete_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stunumber', models.CharField(max_length=8)),
                ('gpa', models.CharField(max_length=8)),
            ],
        ),
    ]
