# Generated by Django 2.1 on 2018-10-03 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gv', '0014_studentinfo_subjectinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('utilization_time', models.CharField(max_length=30)),
                ('area', models.CharField(choices=[['西池袋', '西池袋'], ['東池袋', '東池袋']], max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('number_of_people', models.IntegerField()),
                ('evaluation_quality', models.IntegerField()),
                ('evaluation_amount', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('sex', models.CharField(max_length=30)),
                ('photograph_shine', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
