# Generated by Django 2.1 on 2018-09-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentInfo',
        ),
    ]
