# Generated by Django 2.1 on 2018-09-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gv', '0004_delete_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=8)),
                ('student_grade', models.IntegerField()),
                ('enteryear', models.IntegerField()),
                ('seasons', models.IntegerField()),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
