# Generated by Django 2.1 on 2018-09-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0005_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectnum', models.CharField(max_length=15)),
                ('subjectname', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=20)),
                ('managementnum', models.CharField(max_length=20)),
                ('grade_score', models.CharField(max_length=10)),
                ('result_score', models.CharField(max_length=10)),
                ('gpa_data', models.CharField(max_length=20)),
                ('category1', models.CharField(max_length=30)),
                ('category2', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=10)),
                ('last_login', models.CharField(max_length=20)),
                ('unit_int', models.IntegerField()),
                ('year_int', models.IntegerField()),
                ('grade_score_int', models.IntegerField()),
                ('result_score_int', models.IntegerField()),
                ('gpa_int', models.FloatField()),
            ],
        ),
    ]
