# Generated by Django 2.1 on 2018-09-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0006_subjectinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentInfo',
        ),
        migrations.DeleteModel(
            name='subjectInfo',
        ),
    ]
