# Generated by Django 2.1 on 2018-09-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0010_studentinfo_subjectinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectinfo',
            name='stu_id',
        ),
        migrations.DeleteModel(
            name='studentInfo',
        ),
        migrations.DeleteModel(
            name='subjectInfo',
        ),
    ]
