# Generated by Django 2.1 on 2018-09-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gv', '0013_auto_20180915_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('student_grade', models.IntegerField()),
                ('enteryear', models.IntegerField()),
                ('seasons', models.IntegerField()),
                ('gpa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='subjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectnum', models.CharField(max_length=15)),
                ('managementnum', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=10)),
                ('subjectname', models.CharField(max_length=40)),
                ('unit_int', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('grade_score_int', models.IntegerField()),
                ('result_score_int', models.IntegerField()),
                ('year_int', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=20)),
                ('gpa_int', models.FloatField()),
                ('category1', models.CharField(max_length=30)),
                ('category2', models.CharField(max_length=30)),
                ('last_login', models.CharField(max_length=20)),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gv.studentInfo')),
            ],
        ),
    ]
