# Generated by Django 2.1 on 2018-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gv', '0015_food_pool_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_pool',
            name='area',
            field=models.CharField(choices=[['池袋駅・北', '池袋駅・北'], ['池袋駅・東', '池袋駅・東'], ['池袋駅・南', '池袋駅・南'], ['池袋駅・西', '池袋駅・西']], max_length=30),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='duration',
            field=models.IntegerField(choices=[[10, '~10分'], [15, '11分~20分'], [25, '21分~30分'], [30, '31分-60分'], [61, '1時間以上']]),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='evaluation_amount',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='evaluation_quality',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='genre',
            field=models.CharField(choices=[['和食', '和食'], ['洋食', '洋食'], ['中華料理', '中華料理'], ['ラーメン', 'ラーメン'], ['カレー', 'カレー'], ['焼肉', '焼肉'], ['鍋', '鍋'], ['居酒屋・ダイニングバー', '居酒屋・ダイニングバー'], ['ファミレス', 'ファミレス']], max_length=30),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='number_of_people',
            field=models.IntegerField(choices=[[1, '1人'], [2, '2人'], [3, '3人'], [4, '4人'], [5, '5人'], [6, '6人'], [10, '7人~13人'], [14, '14人~']]),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='photograph_shine',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='price',
            field=models.IntegerField(choices=[[100, '~200円'], [300, '201円~400円'], [500, '401円~600円'], [700, '601円~800円'], [900, '801円~1000円'], [1250, '1001円~1500円'], [1750, '1501円~2000円'], [2500, '2001円~3000円'], [3001, '3001円~'], [4001, '4001円~']]),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='sex',
            field=models.CharField(choices=[['女', '女'], ['男', '男'], ['その他', 'その他']], max_length=30),
        ),
        migrations.AlterField(
            model_name='food_pool',
            name='utilization_time',
            field=models.CharField(choices=[['朝食', '朝食'], ['ブランチ', 'ブランチ'], ['昼食', '昼食'], ['おやつ', 'おやつ'], ['夕食', '夕食'], ['夜食', '夜食'], ['飲み会', '飲み会']], max_length=30),
        ),
    ]
